Rails.application.routes.draw do
  get 'drinks/index'
  get 'drinks/show'
  get 'drinks/new'
  get 'drinks/edit'
  get 'drinks/create'
  get 'drinks/update'
  get 'drinks/destroy'
  get 'food/index'
  get 'food/show'
  get 'food/new'
  get 'food/edit'
  get 'food/create'
  get 'food/update'
  get 'food/destroy'
  get '/fridges', to: 'fridges#index'
  get 'fridges/:id', to: 'fridges#show'
  get 'fridges/new', to: 'fridges#new'
  get 'fridges/:id/edit', to: 'fridge#edit'
  post 'fridges/create', to: 'fridges#create'
  put 'fridges/update', to: 'fridges#update'
  delete 'fridges/destroy', to: 'fridges#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
